---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wildlife-api-env
  namespace: wildlife-api
spec:
  encryptedData: 
    DATABASE_URL: AgBUv5XDszHgxONVxa+VC41hsPx2sMJ8myubrsIBqjBCfoDgnm/IMm80JG1JC1katNwGVduT5dF/3TrxQMu2RDNkdwn67YTESpGLPWQPtnxk3eJ9xy0mOcDILinQXH20YlzvHPVaDbOKD3iZEskqbOaVLKQB58GwvQNRCtkTa0upF/8AWc2PXFTqOr9DbtI0uzu6GdOJ/bMFD41mS8qcOPRmcX2SfZkltIqMFiWmQdfcFKnaYC9vVn1DIYy4osRwbyDzaX0HRcj15I1M9lfwYEaTr8Ell52gYzyj9osaBuArukUR2TQGn+xH9ChPz6te2QhVtpZOsWtYr9p/9BNT3On3teC1DtMQyi5/jiL+EszKmzTCbORMjvvHHh0miZAiaq4eV4rBfJBVJbRgHaIy0AwTNOmfDdl7553wSWb5vUPV+1KZTf7+0P+vkq27E943LmMadjef9SZ8QdNvXsHRk9ItGPyZFjO30Larc1q2STwjFzbgUuHhG38uwvrWw/patyCjn5bgTcXEAUkEsAnS8hKtFmWffCOr9cBzqjP/5J/YACuAc+e7botM82LbHGaQVY+8Pt75MAyMJ/doGckpN4UwXYT4yE1Bt736iLbH8xRBmSmD3jRszL+C5IzV8y6Ytr5Fsgi7lpv+CS76z1giCIRdKXw3tuDhW42TKjuhRGDVK/8/kcBZ+h/05coNV8AxRFOqyiK33YFWPx2Mhp572mMVG9j2YM2H2yRo9ZxXd9youPrdduW4W2CUsUOxdrwxfTnmPEtSy3MsBE7Wh1ilhFD3PI5OsTEbK5TvQzHia4oNq5xwMM8LGEJzFKLFEBQCV8B/XWtkvCurz7PkpxejLxujuaXYP6zZv1DUNKnrRMBrX68AjVrllK9pxA==
---
apiVersion: v1
kind: Secret
metadata:
  name: wildlife-api-env
stringData:
  DATABASE_URL: test
